version: '3.8'

services:
  postgres:
    container_name: container-ohlc-postgres
    build:
      context: .
      dockerfile: docker/pgvector/Dockerfile
    image: custom-pgvector
    hostname: localhost
    ports:
      - "5621:5432"  # Map port 5621 on the host to port 5432 in the container
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"