name: Fly Deploy Frontend

on:
  push:
    branches:
      - main
    paths:
      - 'app/**'  # Trigger deployment only for changes in the frontend directory
  pull_request:
    branches:
      - main
    paths:
      - 'app/**'  # Trigger deployment only for pull requests affecting the frontend directory

jobs:
  deploy:
    name: Deploy Frontend App
    runs-on: ubuntu-latest
    concurrency: deploy-group    # Ensure only one deployment action runs at a time
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
